### PR TITLE
Add support for getting all occurences

### LINKED ISSUE #6: Add all_occurrences
Any reason for the requirement to specify occurrences between dates? How about adding `all_occurrences`?

### PR DESCRIPTION
**Pull request by espen**
Fixes #6

### CODE REVIEW

**Comment by jnraine** [comment]
Looks good @espen. How performant is this for events that recur indefinitely? Or very often recurring events?

**Comment by espen** [comment]
IceCube raises : "All recurrence rules must specify .until or .count to use `all_occurrences'".

**Comment by jnraine** [comment]
Ah, good to hear. How about creating an exception that wraps that particular case so we don't leak the IceCube exceptions? Tests look good, so once that is in I'll merge it.

**Comment by espen** [comment]
What kind of exception and message should be raised then? Looks like the exception can only be identified by message, so any changes in IceCube would then result in the original exception being raised.

Also I assume there are many other exceptions that can occur in IceCube after occurrences_between or all_occurrences. Should all be wrapped then?

**Comment by jnraine** [comment]
Good questions. I was hoping the IceCube exception would be more specifically typed (e.g., `IceCube::InfiniteOccurrenceError`). Matching against the message would be unfortunate, though perhaps better than nothing in this case. 

Alternately, any IceCube exception could be wrapped into a generic icalendar-recurrence exception, passing on the message. At a later date, we could handle additional error handling for IceCube exceptions and the consumer's of the library would not need to modify their rescue code. Something along these lines:

```ruby
def all_occurrences
  ice_cube_occurrences = ice_cube_schedule.all_occurrences

  ice_cube_occurrences.map do |occurrence|
    convert_ice_cube_occurrence(occurrence)
  end
rescue IceCube::StandardError => e
  if e.message == "All recurrence rules must specify .until or .count to use `all_occurrences'"
    raise Icalendar::Recurrence::InfiniteOccurrenceError.new(e.message)
  else
    raise Icalendar::Recurrence::StandardError.new(e.message)
  end
end

# elsewhere
module Icalendar
  module Recurrence
    class StandardError < ::StandardError; end
    class InfiniteOccurrenceError < StandardError; end
  end
end
```

_The above code is a sketch for brainstorming and may not execute._

What do you think?

**Comment by espen** [comment]
I'm not sure. I think it's best I just leave the code as is and you can decide on how to handle errors in general.

**Pull request merged**
